#### **Token Embeddings**
##### **Token Embeddings are converts each token id into dense numerical vector representation that are neural network can learn from.**

In [1]:
import torch

#small vocabulary
vocab = {
    "I": 0,
    "love": 1,
    "LLMs": 2,
    "learning": 3,
    "Python": 4
}

## create token ids
input_ids = torch.tensor([0,1,2,3])

In [5]:
## create a embedding layer using vocab size and size of each vector is 4
import torch.nn as nn

vocab_size = len(vocab)
embedding_dim = 4

#embedding layer
torch.manual_seed(123)
embedding_layer = nn.Embedding(vocab_size,embedding_dim)
print(embedding_layer)

Embedding(5, 4)


In [9]:
## weights
embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880],
        [ 1.5810,  1.3010,  1.2753, -0.2010],
        [-0.1606, -0.4015,  0.6957, -1.8061],
        [-1.1589,  0.3255, -0.6315, -2.8400],
        [-0.7849, -1.4096, -0.4076,  0.7953]], requires_grad=True)

In [10]:
# Get embeddings for input_ids
input_ids

tensor([0, 1, 2, 3])

In [11]:
# Print the embeddings for input_ids
embedding_layer(input_ids)

tensor([[ 0.3374, -0.1778, -0.3035, -0.5880],
        [ 1.5810,  1.3010,  1.2753, -0.2010],
        [-0.1606, -0.4015,  0.6957, -1.8061],
        [-1.1589,  0.3255, -0.6315, -2.8400]], grad_fn=<EmbeddingBackward0>)

In [26]:
# Print the shape of the embeddings
embedding = embedding_layer(torch.tensor(list(vocab.values())))
embedding.shape

torch.Size([5, 4])

In [16]:
# Check whether the embedding weights are trainable
embedding_layer.weight.requires_grad

True