### ***Token Embeddings***

#### **Token Embeddings means converts each token id into dense numerical vector that the neural network can learn from.**

##### ***Word2vec-google-news-300***
##### Example Pre-trained Token Embedding Model.
##### Dataset contains roughly 300 billion words
##### 3 Million Unique Words
##### 300 Dimension Vector

In [1]:
import gensim.downloader as api

model = api.load("word2vec-google-news-300")

In [2]:
vocab_vector = model
## Model is dataset like input as Word and output as dense Numberical Vector.

In [3]:
### Let's test the Number Of Dimensional of each vector
print(len(vocab_vector['King']))

300


In [4]:
print(len(vocab_vector))

3000000


#### **Similar Words**

In [5]:
### get similar words for King+Woman-Man = ?

print(vocab_vector.most_similar(positive=['King','Woman'],negative=['Man'],topn=10))

[('Queen', 0.4929387867450714), ('Tupou_V.', 0.45174285769462585), ('Oprah_BFF_Gayle', 0.4422132968902588), ('Jackson', 0.440250426530838), ('NECN_Alison', 0.4331282675266266), ('Whitfield', 0.42834725975990295), ('Ida_Vandross', 0.42084527015686035), ('prosecutor_Dan_Satterberg', 0.420758992433548), ('martin_Luther_King', 0.42059651017189026), ('Coretta_King', 0.4202733635902405)]


In [13]:
### Let's similarity between Words
print(vocab_vector.similarity("Cat","Dog"))
print(vocab_vector.similarity("Milk","Tea"))
print(vocab_vector.similarity("boy","girl"))
print(vocab_vector.similarity("keyboard","desktop"))

0.60611075
0.3800191
0.8543272
0.4540027


In [15]:
## Lets's calculate the magnitude of two words

import numpy as np 

word1 = "woman"
word2 = "man"

word3 = "dog"
word4 = "cat"

word5 = "book"
word6 = "pen"

###Calculate the Vector Difference
vector_difference1 = model[word1]-model[word2]
vector_difference2 = model[word3]-model[word4]
vector_difference3 = model[word5]-model[word6]

### Magnitude
magnitude1 = np.linalg.norm(vector_difference1)
magnitude2 = np.linalg.norm(vector_difference2)
magnitude3 = np.linalg.norm(vector_difference3)

print(f"Magnitude of {word1} and {word2} is:",magnitude1)
print(f"Magnitude of {word3} and {word4} is:",magnitude2)
print(f"Magnitude of {word5} and {word6} is:",magnitude3)

Magnitude of woman and man is: 1.727951
Magnitude of dog and cat is: 2.0815337
Magnitude of book and pen is: 3.3038652


In [17]:
### Let's build embedding weights matrix with an Example. Suppose Input Tokens are 2,3,5, and 1.
import torch
input_ids = torch.tensor([2,3,5,1]) #Every Token ID associated with a word



In [18]:
## for Simple Embedding Weights matrix, let's take the size of vocab is 6 and vector dim is 3
## Gpt-2 was trained on 50,257 tokens as vocab size and vector dim is 768. 

In [19]:
vocab_size = 6
output_dim = 3 #size of each token

In [35]:
#Using the Pytorch we can initalize the Embedding Layer by passing the vocab size and output dim ,
#it will create a lookup table like embedding weight matrix with vocab size as row and output dim as column.
torch.manual_seed(123) #manual seed is fixed will not change for every execution.
embedding_layer = torch.nn.Embedding(vocab_size,output_dim)
print(embedding_layer)

Embedding(6, 3)


In [39]:
### let's see the weights
embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

In [40]:
### Weights of Embedding layer consists of random value's, 
# these values will optimize during the LLM Training

In [ ]:
##let's get the vector using the token id is 3
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [43]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
