#### ***Self Attention Mechanism With Trainable Weights***

In [194]:
import torch


inputs = torch.tensor([
    [0.8, 0.1, 0.2],   #← Your
    [1.0, 0.7, 0.8],   #← Journey
    [0.7, 1.0, 0.3],   #← Starts
    [0.2, 0.2, 0.6],   #← with
    [0.3, 0.4, 0.9],   #← one
    [0.8, 0.9, 1.0]    #← step
])

In [195]:
x_2 = inputs[1]

d_in = inputs.shape[1]
d_out = 2
d_in

3

In [196]:
torch.manual_seed(123)

W_query = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)


In [197]:
print(W_query)

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])


In [198]:
print(W_key)

Parameter containing:
tensor([[0.1366, 0.1025],
        [0.1841, 0.7264],
        [0.3153, 0.6871]])


In [199]:
print(W_value)

Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])


In [200]:
x_2 ##input embedding for Journey

tensor([1.0000, 0.7000, 0.8000])

In [201]:
query_2 = x_2@W_query
key_2 = x_2@W_key
value_2 = x_2@W_value

print(key_2)

tensor([0.5176, 1.1607])


In [202]:
### Let's do for all inputs
queries = inputs@W_query
keys = inputs@W_key
values = inputs@W_value


In [203]:
print("Shape:",queries.shape)
print("Queries:",queries)

Shape: torch.Size([6, 2])
Queries: tensor([[0.2769, 0.6554],
        [0.5315, 1.6918],
        [0.4811, 1.3101],
        [0.1539, 0.7609],
        [0.2561, 1.2103],
        [0.5374, 1.8995]])


In [204]:
print("Shape:",keys.shape)
print("Keys:",keys)

Shape: torch.Size([6, 2])
Keys: tensor([[0.1907, 0.2920],
        [0.5176, 1.1607],
        [0.3742, 1.0043],
        [0.2533, 0.5780],
        [0.3983, 0.9397],
        [0.5902, 1.4229]])


In [205]:
print("Shape:",values.shape)
print("Values:",values)

Shape: torch.Size([6, 2])
Values: tensor([[0.1159, 0.3630],
        [0.3920, 1.1398],
        [0.4049, 0.7876],
        [0.1496, 0.6161],
        [0.2560, 0.9643],
        [0.4638, 1.3463]])


In [206]:
### let's get the Attention Score for Query 2(journey) = queries_2@Keys

queries_2 = queries[1]
print("Query:",queries_2)

keys_2 = keys[2]
print("Key:",keys_2)

Query: tensor([0.5315, 1.6918])
Key: tensor([0.3742, 1.0043])


### **Attention Score = how strongly one token should pay attention to another token.**

In [207]:
attn_2 = torch.dot(queries_2,key_2)
attn_2

tensor(2.2387)

In [208]:
# lets implement to all keys
attn_score_2 = queries_2@keys.T
attn_score_2

tensor([0.5954, 2.2387, 1.8980, 1.1125, 1.8015, 2.7209])

In [209]:
## for all queries and keys
attn_score = queries @ keys.T
print(attn_score)

tensor([[0.2442, 0.9040, 0.7618, 0.4490, 0.7262, 1.0960],
        [0.5954, 2.2387, 1.8980, 1.1125, 1.8015, 2.7209],
        [0.4744, 1.7697, 1.4958, 0.8792, 1.4228, 2.1481],
        [0.2516, 0.9629, 0.8218, 0.4788, 0.7764, 1.1736],
        [0.4023, 1.5373, 1.3113, 0.7644, 1.2393, 1.8732],
        [0.6572, 2.4828, 2.1088, 1.2341, 1.9990, 3.0199]])


In [210]:
## let's implement the normalization for the attention score for Journey. 
d_k = keys.shape[-1]#column
print(d_k)
attn_weight_2 = torch.softmax(attn_score_2/d_k**0.5,dim=-1)
print(attn_weight_2)
print("Sum:",attn_weight_2.sum())

2
tensor([0.0667, 0.2132, 0.1676, 0.0962, 0.1565, 0.2998])
Sum: tensor(1.)


In [211]:
attn_weight = torch.softmax(attn_score/d_k**0.5,dim=-1)
print(attn_weight)

tensor([[0.1187, 0.1893, 0.1712, 0.1372, 0.1669, 0.2168],
        [0.0667, 0.2132, 0.1676, 0.0962, 0.1565, 0.2998],
        [0.0826, 0.2063, 0.1700, 0.1099, 0.1615, 0.2697],
        [0.1150, 0.1902, 0.1722, 0.1351, 0.1667, 0.2208],
        [0.0904, 0.2017, 0.1719, 0.1168, 0.1634, 0.2558],
        [0.0594, 0.2161, 0.1658, 0.0894, 0.1535, 0.3159]])


#### **Why SQRT**

In [212]:
att_sc = torch.tensor([-0.1,0.2,-0.3,-0.2,0.5])
weights = torch.softmax(att_sc,dim = -1)
print(weights) ## sounds good

new_att_sc = att_sc*8
new_weights = torch.softmax(new_att_sc,dim = -1)
print(new_weights)## becomes peaky

tensor([0.1696, 0.2290, 0.1389, 0.1535, 0.3091])
tensor([0.0075, 0.0821, 0.0015, 0.0033, 0.9055])


In [213]:
### The variance of between the dot product of key and query is higher
## the increase variance grows with dimensions. 
### divide by the sqrt , keeps the variance close to 1.

In [214]:
### let's see the context vector for journey

context_vect_2 = attn_weight_2@values
print(context_vect_2)

tensor([0.3527, 1.0130])


In [215]:
import torch.nn as nn

class SimpleAttention_V1(nn.Module):

    def __init__(self,d_in,s_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in,d_out),requires_grad = False)
        self.W_key = nn.Parameter(torch.rand(d_in,d_out),requires_grad = False)
        self.W_value = nn.Parameter(torch.rand(d_in,d_out),requires_grad = False)

    def forward(self,x):
        keys = x@self.W_key
        queries = x@self.W_query 
        values = x@self.W_value


        attention_scores = queries@keys.T
        attention_weights = torch.softmax(attention_scores/keys.shape[-1]**0.5,dim= -1)
        context_vectors = attention_weights@values

        return context_vectors

In [216]:
torch.manual_seed(123)
sa_v1 = SimpleAttention_V1(d_in,d_out)
print(sa_v1(inputs))

tensor([[0.3210, 0.9309],
        [0.3527, 1.0130],
        [0.3421, 0.9855],
        [0.3229, 0.9354],
        [0.3371, 0.9720],
        [0.3579, 1.0267]])


In [217]:
import torch.nn as nn

class SimpleAttention_V2(nn.Module):

    def __init__(self,d_in,s_out,qvk_bias = False):
        super().__init__()
        self.W_query = nn.Linear(d_in,d_out,bias = qvk_bias)
        self.W_key = nn.Linear(d_in,d_out,bias = qvk_bias)
        self.W_value = nn.Linear(d_in,d_out,bias = qvk_bias)

    def forward(self,x):
        keys = self.W_key(x)
        queries = self.W_query(x) 
        values = self.W_value(x)


        attention_scores = queries@keys.T
        attention_weights = torch.softmax(attention_scores/keys.shape[-1]**0.5,dim= -1)
        context_vectors = attention_weights@values

        return context_vectors

In [218]:

sa_v2 = SimpleAttention_V2(d_in,d_out)
print(sa_v2(inputs))

tensor([[0.6284, 0.3729],
        [0.6371, 0.3871],
        [0.6316, 0.3788],
        [0.6310, 0.3784],
        [0.6351, 0.3851],
        [0.6390, 0.3911]], grad_fn=<MmBackward0>)
